.unit: &unit
  image: python:3.11
  before_script:
    - python --version
    - python -m pip install --upgrade pip
    - pip install tox
  stage: test
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'

test-flake8:
  <<: *unit
  script:
    - tox -e flake8

test-mypy:
  <<: *unit
  script:
    - tox -e mypy

test-pytest:
  <<: *unit
  script:
    - tox -e pytest
